### ISSUE TITLE
Frequent crashes on some large maps

### ISSUE THREAD

**Issue by ScratcherAwesomeMinecraft2005** [IcyStarFrost/Lambda-Players#82]
### Description
Having Lambda Players on certain large maps will most likely crash the game within a few minutes to an hour, even without MWS. Surprisingly, this happens a lot more often than with Zeta Players.

A good example of a map that experiences this issue is [gm_functional_flatgrass_sfoh](https://steamcommunity.com/sharedfiles/filedetails/?id=2823263277).

### To reproduce
1. Launch the example map.
2. Make sure MWS is turned off.
3. Spawn a few Lambda Players (I usually spawn 7).
4. Wait...
5. Crash!

**Comment by IcyStarFrost** [comment]
My first assumption would because of pathfinding. There's likely so much nav areas and lambdas that the game just cant handle and hence will crash. 

This is a assumption so this isn't a definitive answer but it is a likely one. When I come back to working on Lambdas I will test in a dedicated server.

**Comment by IcyStarFrost** [comment]
I've read the comments of that map and the blame seems to be shifting to the map itself. Constant complaints of horrid FPS and crashes. In this case there is nothing I can do to fix this.

I have also played in the map for more than 30 minutes and haven't seen a problem at all with 12 Lambdas. My suggestion is play smaller maps and make sure you are on the 64x branch of Garry's Mod.
